# Generated by Django 6.0.3 on 2026-03-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_tenure_months', models.IntegerField()),
                ('loan_purpose', models.CharField(max_length=50)),
                ('loan_type', models.CharField(max_length=50)),
                ('residence_type', models.CharField(max_length=50)),
                ('avg_dpd_per_dm', models.IntegerField(default=0)),
                ('total_loan_months', models.IntegerField(default=0)),
                ('credit_utilization_ratio', models.FloatField(default=0)),
                ('dmtlm', models.FloatField(default=0)),
                ('default_probability', models.FloatField()),
                ('credit_score', models.IntegerField()),
                ('rating', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
